#! /bin/bash

electron-installer-dmg ./out/tea-package-builder-darwin-arm64/tea-package-builder.app \
"TeaPackageBuilder" \
--out="./out/electron-installer-dmg/" \
--background="./images/installBackground658.png" \
--icon="./images/logo.icns" \
--title="Tea Package Builder" \
--overwrite \
--debug